apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: vmmaia/booksearch-backend
          env:
            - name: MONGO_URI
              value: 'mongodb://backend-mongo-srv:27017/backend'
            - name: JWT_EXPIRES_IN
              value: '15m'
            - name: SERVER_PORT
              value: '5000'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: JWT_REFRESH_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-refresh-secret
                  key: JWT_REFRESH_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: backend-srv
spec:
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 5000
      targetPort: 5000
